// nomesLegiveis.ts
export const nomesLegiveis: Record<string, string> = {
    kitFotovoltaico: "Kit Fotovoltaico",
    valorProjeto: "Valor do Projeto",
    valorPlacaAdvertencia: "Placa de Advertência",
    margemLucroBruta: "Margem de Lucro Bruta",
    desconto: "Desconto",
    porcentagemComissao: "Porcentagem de Comissão",
    editEletricista: "Editar Eletricista",
    editInfra: "Editar Infraestrutura",
    editComissao: "Editar Comissão",
    valorEletricistaUnit: "Valor por Eletricista",
    valorInfraUnit: "Valor por Infraestrutura",
    valorComissaoUnit: "Valor por Comissão",
    entrada: "Entrada",
    juros: "Juros (R$)",
    qtdParcelas: "Quantidade de Parcelas",
    parcelaSelecionada: "Parcela Selecionada",
    quantidadePlacas: "Quantidade de Placas",
    totalCusto: "Total de Custo",
    totalVenda: "Total de Venda",
    totalLucro: "Lucro Total",
    lucroFinalComDescontoEComissao: "Lucro Final com Desconto e Comissão",
    faturamentoBrutoPorModulo: "Faturamento Bruto por Módulo",
    faturamentoLiquidoPorModulo: "Faturamento Líquido por Módulo",
    valorFinanciado: "Valor Financiado",
  };

export const nomesLegiveisProjeto: Record<string, string> = {
  áreaMinimaTotal: "Área mínima total",
  comprimento: "Comprimento",
  consumoAPagar: "Consumo a pagar",
  consumoMedioDia: "Consumo médio diário",
  consumoMedioMes: "Consumo médio mensal",
  consumoTempoReal: "Consumo em tempo real",
  consumoMensal: "Consumo Mensal",
  excedente: "Excedente",
  fioB: "Valor do Fio B",
  fioBCalculado: "Fio B calculado com percentual",
  fioBaPagar: "Fio B a pagar",
  geracaoMensal: "Geração mensal",
  iluminacaoPublica: "Iluminação pública",
  injeçãoEstimada: "Injeção estimada",
  largura: "Largura",
  modo: "Modo de cálculo (Recomendado/Manual)",
  modoManualDimensao: "Dimensão em modo manual",
  nomeProjeto: "Nome do projeto",
  percentualFioB: "Percentual do Fio B",
  percentualImposto: "Percentual de imposto",
  percentualInjeção: "Percentual de injeção",
  potênciaInversor: "Potência do inversor",
  potênciaPico: "Potência pico",
  potênciaPlaca: "Potência da placa",
  qtdPlacas: "Quantidade de placas",
  tarifaMínima: "Tarifa mínima",
  tipoLigacao: "Tipo de ligação (Monofásico, etc.)",
  totalComImposto: "Total com imposto",
  totalSemImposto: "Total sem imposto",
  valorKWh: "Valor do kWh"
}
  